theme: jekyll-theme-cayman
title: Airbnb activities in Seattle
![My Picture](buildings.jpg)
description: A blog dedicated to educational content and is a part of an exercise which needs to be done for an exam.

